### PR TITLE
Add support for queries with joins

### LINKED ISSUE #19: Not compatible for queries with joins
Trying to do so results on the following error:

```
sql: 'select "test".* from "test" inner join "test3" on "test"."id" = "test3”."model1" where "test3”."model1" = ? and ("deleted_at" is null or "restored_at" is not null) limit ?’

Error: SQLITE_ERROR: ambiguous column name: deleted_at
```

### PR DESCRIPTION
**Pull request by ricardogama**
This PR closes #19. A condition is added to check if the model or collection contains the knex query builder, adding the table prefix to the soft delete attributes clauses.

### CODE REVIEW

**Comment by ricardogama** [comment]
@apechimp and @apolishch please review.

**Comment by apolishch** [comment]
@ricardogama Thank you for the contribution!

**Comment by apolishch** [comment]
published as 3.2.0

**Comment by ricardogama** [comment]
You're welcome, cheers!

**Pull request merged**
