### PR TITLE
Override model.fetch as well

### LINKED ISSUE #6: Override Model .fetch and .fetchAll

### PR DESCRIPTION
**Pull request by apechimp**
This resolves #6 and overhauls the method for returning only things which haven't been soft deleted so that it acts as a sql query instead of mutating the results returned from the database. This approach has a few advantages which follow.

- results of a fetch now correctly report length
- `fetchOne` and `model.fetch` no longer return `null` if there is a thing which has been soft deleted returned first.
- `fetchOne` does not need its own override (bookshelf delegates to the model for this).

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers

**Comment by apechimp** [comment]
Note that after this is merged, I will rev a minor version and publish the module.

**Comment by apolishch** [comment]
:+1:

**Comment by DannyDouglass** [comment]
:guitar:

**Pull request merged**
