### PR TITLE
Leave this.soft untouched for other modules compat

### PR DESCRIPTION
**Pull request by jucrouzet**
Leaving this.soft to the original value allow other modules (like validation or etc.) to have the name of the soft deletion fields.

### CODE REVIEW

**Comment by jucrouzet** [comment]
@apolishch : Maybe it's a good idea to add this before publishing ?

**Comment by scarney81** [comment]
@jucrouzet - I'll ensure this gets out in a timely fashion once accepted

**Comment by apolishch** [comment]
:+1:

**Comment by apolishch** [comment]
@jucrouzet this is released

**Comment by jucrouzet** [comment]
Thanks again !

**Comment by apechimp** [comment]
This is apparently the cause of #22. Why does `softActivated` need to be global? why can't we just use an `_` property of the model?

**Pull request merged**
