### PR TITLE
Handle passing an array for columns name

### PR DESCRIPTION
**Pull request by jucrouzet**
Passing an array like `['myDeletionColumn', 'myRestoredColumn']` instead of `true` to the `soft` property allow user to specify the deletion/restore columns names.

### CODE REVIEW

**Comment by apolishch** [comment]
@jucrouzet Thanks for the contribution. Looks great! Merging

**Comment by jucrouzet** [comment]
yw. 
Do you plan publishing it to npm ?

Thanks !

**Comment by apolishch** [comment]
@jucrouzet thanks for the reminder. A new version will go up on npm today/tomorrow.

**Comment by jucrouzet** [comment]
Hello,

Sorry to bother you again, but I'm working on a node-bookshelf-soft-delete dependant project and I'd like to switch again on the npm versionned url instead of a github url.
Do you think that a npm publish will be done soon ?

Thank you !

**Comment by scarney81** [comment]
@jucrouzet - apologies for the delay. I've just published this to npm as version `3.0.0`.

Thanks again for the contribution!
Seth

**Comment by jucrouzet** [comment]
Thanks a lot

**Pull request merged**
